In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a=a+2
print(a)
a=a*3
print(a)
a=a/2
print(a)

[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4.5  6.   7.5  9.  10.5]


In [5]:
arr=np.array([1,2,3,6,4,5])
r=arr[::-1]
print(r)

[5 4 6 3 2 1]


In [6]:
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = values[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
mx, ix = most_frequent(x)
my, iy = most_frequent(y)
print(f'Most frequent value in x: {mx}, Indices: {ix}')
print(f'Most frequent value in y: {my}, Indices: {iy}')

Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [8]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [11]:
Krishna=np.linspace(10,100,25)
print(Krishna)
print(f'Total dimensions:{Krishna.ndim}')
print(f'Shape: {Krishna.shape}')
print(f'Total elements: {Krishna.size}')
print(f'Data type: {Krishna.dtype}')
print(f'Total bytes: {Krishna.nbytes}')
print('Transpose of the array :',Krishna.reshape(len(Krishna),1))
print('Transpose of the array :',Krishna.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Total dimensions:1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose of the array : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose of the array : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
ucs420_Krishna = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_Krishna))
print("Median:", np.median(ucs420_Krishna))
print("Max:", np.max(ucs420_Krishna))
print("Min:", np.min(ucs420_Krishna))
print("Unique Elements:", np.unique(ucs420_Krishna))
reshaped_ucs420_Krishna = ucs420_Krishna.reshape(4, 3)
print("Reshaped:\n", reshaped_ucs420_Krishna)
resized_ucs420_Krishna = np.resize(ucs420_Krishna, (2, 3))
print("Resized:\n", resized_ucs420_Krishna)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
 [[10 20 30]
 [40 50 60]]
